import { DataObjectArray, PortObjectArray } from "./types";

export const cards: DataObjectArray = [
  { key: "3DES", value: "Triple Digital Encryption Standard" },
  { key: "AAA", value: "Authentication, Authorization, and Accounting" },
  { key: "ABAC", value: "Attribute-based Access Control" },
  { key: "ACL", value: "Access Control List" },
  { key: "AES", value: "Advanced Encryption Standard" },
  { key: "AES256", value: "Advanced Encryption Standards 256bit" },
  { key: "AH", value: "Authentication Header" },
  { key: "AI", value: "Artificial Intelligence" },
  { key: "AIS", value: "Automated Indicator Sharing" },
  { key: "ALE", value: "Annualized Loss Expectancy" },
  { key: "AP", value: "Access Point" },
  { key: "API", value: "Application Programming Interface" },
  { key: "APT", value: "Advanced Persistent Threat" },
  { key: "ARO", value: "Annualized Rate of Occurrence" },
  { key: "ARP", value: "Address Resolution Protocol" },
  { key: "ASLR", value: "Address Space Layout Randomization" },
  { key: "ASP", value: "Active Server Page" },
  { key: "ATT&CK", value: "Adversarial Tactics, Techniques," },
  { key: "AUP", value: "Acceptable Use Policy" },
  { key: "AV", value: "Antivirus" },
  { key: "BASH", value: "Bourne Again Shell" },
  { key: "BCP", value: "Business Continuity Planning" },
  { key: "BGP", value: "Border Gateway Protocol" },
  { key: "BIA", value: "Business Impact Analysis" },
  { key: "BIOS", value: "Basic Input/Output System" },
  { key: "BPA", value: "Business Partnership Agreement" },
  { key: "BPDU", value: "Bridge Protocol Data Unit" },
  { key: "BYOD", value: "Bring Your Own Device" },
  { key: "CA", value: "Certificate Authority" },
  { key: "CAC", value: "Common Access Card" },
  {
    key: "CAPTCHA",
    value:
      "Completely Automated Public Turing Test to Tell Computers and Humans Apart",
  },
  { key: "CAR", value: "Corrective Action Report" },
  { key: "CASB", value: "Cloud Access Security Broker" },
  { key: "CBC", value: "Cipher Block Chaining" },
  { key: "CBT", value: "Computer-based Training" },
  { key: "CCMP", value: "Counter-Mode/CBC-Mac Protocol" },
  { key: "CCTV", value: "Closed-Circuit Television" },
  { key: "CERT", value: "Computer Emergency Response Team" },
  { key: "CFB", value: "Cipher Feedback" },
  { key: "CHAP", value: "Challenge Handshake Authentication Protocol" },
  { key: "CIO", value: "Chief Information Officer" },
  { key: "CIRT", value: "Computer Incident Response Team" },
  { key: "CIS", value: "Center for Internet Security" },
  { key: "CMS", value: "Content Management System" },
  { key: "COOP", value: "Continuity of Operation Planning" },
  { key: "COPE", value: "Corporate Owned Personal Enabled" },
  { key: "CP", value: "Contingency Planning" },
  { key: "CRC", value: "Cyclical Redundancy Check" },
  { key: "CRL", value: "Certificate Revocation List" },
  { key: "CSO", value: "Chief Security Officer" },
  { key: "CSP", value: "Cloud Service Provider" },
  { key: "CSR", value: "Certificate Signing Request" },
  { key: "CSRF", value: "Cross-Site Request Forgery" },
  { key: "CSU", value: "Channel Service Unit" },
  { key: "CTM", value: "Counter-Mode" },
  { key: "CTO", value: "Chief Technology Officer" },
  { key: "CVE", value: "Common Vulnerabilities and Exposures" },
  { key: "CVSS", value: "Common Vulnerability Scoring System" },
  { key: "CYOD", value: "Choose Your Own Device" },
  { key: "DAC", value: "Discretionary Access Control" },
  { key: "DBA", value: "Database Administrator" },
  { key: "DDoS", value: "Distributed Denial of Service" },
  { key: "DEP", value: "Data Execution Prevention" },
  { key: "DER", value: "Distinguished Encoding Rules" },
  { key: "DES", value: "Digital Encryption Standard" },
  { key: "DHCP", value: "Dynamic Host Configuration Protocol" },
  { key: "DHE", value: "Diffie-Hellman Ephemeral" },
  { key: "DKIM", value: "Domain Keys Identified Mail" },
  { key: "DLL", value: "Dynamic Link Library" },
  { key: "DLP", value: "Data Loss Prevention" },
  {
    key: "DMARC",
    value: "Domain Message Authentication Reporting and Conformance",
  },
  { key: "DMZ", value: "Demilitarized Zone" },
  { key: "DNAT", value: "Destination Network Address Transaction" },
  { key: "DNS", value: "Domain Name Service (Server)" },
  { key: "DNSSEC", value: "Domain Name System Security Extensions" },
  { key: "DoS", value: "Denial of Service" },
  { key: "DPO", value: "Data Privacy Officer" },
  { key: "DRP", value: "Disaster Recovery Plan" },
  { key: "DSA", value: "Digital Signature Algorithm" },
  { key: "DSL", value: "Digital Subscriber Line" },
  { key: "EAP", value: "Extensible Authentication Protocol" },
  { key: "ECB", value: "Electronic Code Book" },
  { key: "ECC", value: "Elliptic Curve Cryptography" },
  { key: "ECDHE", value: "Elliptic Curve Diffie-Hellman Ephemeral" },
  { key: "ECDSA", value: "Elliptic Curve Digital Signature Algorithm" },
  { key: "EDR", value: "Endpoint Detection and Response" },
  { key: "EFS", value: "Encrypted File System" },
  { key: "EOL", value: "End of Life" },
  { key: "EOS", value: "End of Service" },
  { key: "ERP", value: "Enterprise Resource Planning" },
  { key: "ESN", value: "Electronic Serial Number" },
  { key: "ESP", value: "Encapsulated Security Payload" },
  { key: "FACL", value: "File System Access Control List" },
  { key: "FDE", value: "Full Disk Encryption" },
  { key: "FPGA", value: "Field Programmable Gate Array" },
  { key: "FRR", value: "False Rejection Rate" },
  { key: "FTP", value: "File Transfer Protocol" },
  { key: "FTPS", value: "Secured File Transfer Protocol" },
  { key: "GCM", value: "Galois Counter Mode" },
  { key: "GDPR", value: "General Data Protection Regulation" },
  { key: "GPG", value: "Gnu Privacy Guard" },
  { key: "GPO", value: "Group Policy Object" },
  { key: "GPS", value: "Global Positioning System" },
  { key: "GPU", value: "Graphics Processing Unit" },
  { key: "GRE", value: "Generic Routing Encapsulation" },
  { key: "HA", value: "High Availability" },
  { key: "HDD", value: "Hard Disk Drive" },
  { key: "HIDS", value: "Host-Based Intrusion Detection System" },
  { key: "HIPS", value: "Host-Based Intrusion Prevention System" },
  { key: "HMAC", value: "Hashed Message Authentication Code" },
  { key: "HOTP", value: "HMAC based One Time Password" },
  { key: "HSM", value: "Hardware Security Module" },
  { key: "HTML", value: "HyperText Markup Language" },
  { key: "HTTP", value: "Hypertext Transfer Protocol" },
  { key: "HTTPS", value: "Hypertext Transfer Protocol over SSL/TLS" },
  { key: "HVAC", value: "Heating, Ventilation, Air Conditioning" },
  { key: "IaaS", value: "Infrastructure as a Service" },
  { key: "ICMP", value: "Internet Control Message Protocol" },
  { key: "ICS", value: "Industrial Control Systems" },
  { key: "IDEA", value: "International Data Encryption Algorithm" },
  { key: "IDF", value: "Intermediate Distribution Frame" },
  { key: "IdP", value: "Identity Provider" },
  { key: "IDS", value: "Intrusion Detection System" },
  { key: "IEEE", value: "Institute of Electrical and Electronics Engineers" },
  { key: "IKE", value: "Internet Key Exchange" },
  { key: "IM", value: "Instant Messaging" },
  { key: "IMAP4", value: "Internet Message Access Protocol v4" },
  { key: "IoC", value: "Indicators of Compromise" },
  { key: "IoT", value: "Internet of Things" },
  { key: "IP", value: "Internet Protocol" },
  { key: "IPSec", value: "Internet Protocol Security" },
  { key: "IR", value: "Incident Response" },
  { key: "IRC", value: "Internet Relay Chat" },
  { key: "IRP", value: "Incident Response Plan" },
  { key: "ISO", value: "International Organization for Standardization" },
  { key: "ISP", value: "Internet Service Provider" },
  { key: "ISSO", value: "Information Systems Security Officer" },
  { key: "ITCP", value: "IT Contingency Plan" },
  { key: "IV", value: "Initialization Vector" },
  { key: "KDC", value: "Key Distribution Center" },
  { key: "KEK", value: "Key Encryption Key" },
  { key: "L2TP", value: "Layer 2 Tunneling Protocol" },
  { key: "LAN", value: "Local Area Network" },
  { key: "LDAP", value: "Lightweight Directory Access Protocol" },
  { key: "LEAP", value: "Lightweight Extensible Authentication Protocol" },
  { key: "MaaS", value: "Monitoring as a Service" },
  { key: "MAC", value: "Message Authentication Code" },
  { key: "MAM", value: "Mobile Application Management" },
  { key: "MAN", value: "Metropolitan Area Network" },
  { key: "MBR", value: "Master Boot Record" },
  { key: "MD5", value: "Message Digest 5" },
  { key: "MDF", value: "Main Distribution Frame" },
  { key: "MDM", value: "Mobile Device Management" },
  { key: "MFA", value: "Multifactor Authentication" },
  { key: "MFD", value: "Multi-Function Device" },
  { key: "MFP", value: "Multi-Function Printer" },
  { key: "MITM", value: "Man in the Middle" },
  { key: "ML", value: "Machine Learning" },
  { key: "MMS", value: "Multimedia Message Service" },
  { key: "MOA", value: "Memorandum of Agreement" },
  { key: "MOU", value: "Memorandum of Understanding" },
  { key: "MPLS", value: "Multi-Protocol Label Switching" },
  { key: "MSA", value: "Measurement Systems Analysis" },
  {
    key: "MSCHAP",
    value: "Microsoft Challenge Handshake Authentication Protocol",
  },
  { key: "MSP", value: "Managed Service Provider" },
  { key: "MSSP", value: "Managed Security Service Provider" },
  { key: "MTBF", value: "Mean Time Between Failures" },
  { key: "MTTF", value: "Mean Time to Failure" },
  { key: "MTTR", value: "Mean Time to Recover" },
  { key: "MTU", value: "Maximum Transmission Unit" },
  { key: "NAC", value: "Network Access Control" },
  { key: "NAS", value: "Network Attached Storage" },
  { key: "NAT", value: "Network Address Translation" },
  { key: "NDA", value: "Non-Disclosure Agreement" },
  { key: "NFC", value: "Near Field Communication" },
  { key: "NFV", value: "Network Functions Virtualization" },
  { key: "NIC", value: "Network Interface Card" },
  { key: "NIDS", value: "Network Based Intrusion Detection System" },
  { key: "NIPS", value: "Network Based Intrusion Prevention System" },
  { key: "NIST", value: "National Institute of Standards & Technology" },
  { key: "NTFS", value: "New Technology File System" },
  { key: "NTLM", value: "New Technology LAN Manager" },
  { key: "NTP", value: "Network Time Protocol" },
  { key: "OAUTH", value: "Open Authorization" },
  { key: "OCSP", value: "Online Certificate Status Protocol" },
  { key: "OID", value: "Object Identifier" },
  { key: "OS", value: "Operating System" },
  { key: "OSI", value: "Open Systems Interconnection" },
  { key: "OSINT", value: "Open Source Intelligence" },
  { key: "OSPF", value: "Open Shortest Path First" },
  { key: "OT", value: "Operational Technology" },
  { key: "OTA", value: "Over The Air" },
  { key: "OTG", value: "On The Go" },
  { key: "OVAL", value: "Open Vulnerability Assessment Language" },
  { key: "OWASP", value: "Open Web Application Security Project" },
  { key: "P12", value: "PKCS #12" },
  { key: "P2P", value: "Peer to Peer" },
  { key: "PaaS", value: "Platform as a Service" },
  { key: "PAC", value: "Proxy Auto Configuration" },
  { key: "PAM", value: "Pluggable Authentication Modules" },
  { key: "PAP", value: "Password Authentication Protocol" },
  { key: "PAT", value: "Port Address Translation" },
  { key: "PBKDF2", value: "Password Based Key Derivation Function 2" },
  { key: "PBX", value: "Private Branch Exchange" },
  { key: "PCAP", value: "Packet Capture" },
  { key: "PCI", value: "DSS Payment Card Industry Data Security Standard" },
  { key: "PDU", value: "Power Distribution Unit" },
  { key: "PEAP", value: "Protected Extensible Authentication Protocol" },
  { key: "PED", value: "Personal Electronic Device" },
  { key: "PEM", value: "Privacy Enhanced Mail" },
  { key: "PFS", value: "Perfect Forward Secrecy" },
  { key: "PFX", value: "Personal Information Exchange" },
  { key: "PGP", value: "Pretty Good Privacy" },
  { key: "PHI", value: "Personal Health Information" },
  { key: "PII", value: "Personally Identifiable Information" },
  { key: "PIV", value: "Personal Identity Verification" },
  { key: "PKCS", value: "Public Key Cryptography Standards" },
  { key: "PKI", value: "Public Key Infrastructure" },
  { key: "POP", value: "Post Office Protocol" },
  { key: "POTS", value: "Plain Old Telephone Service" },
  { key: "PPP", value: "Point-to-Point Protocol" },
  { key: "PPTP", value: "Point-to-Point Tunneling Protocol" },
  { key: "PSK", value: "Pre-Shared Key" },
  { key: "PTZ", value: "Pan-Tilt-Zoom" },
  { key: "QA", value: "Quality Assurance" },
  { key: "QoS", value: "Quality of Service" },
  { key: "PUP", value: "Potentially Unwanted Program" },
  { key: "RA", value: "Registration Authority" },
  {
    key: "RACE",
    value:
      "Research and Development in Advanced Communications Technologies in Europe",
  },
  { key: "RAD", value: "Rapid Application Development" },
  { key: "RADIUS", value: "Remote Authentication Dial-in User Server" },
  { key: "RAID", value: "Redundant Array of Inexpensive Disks" },
  { key: "RAM", value: "Random Access Memory" },
  { key: "RAS", value: "Remote Access Server" },
  { key: "RAT", value: "Remote Access Trojan" },
  { key: "RC4", value: "Rivest Cipher version 4" },
  { key: "RCS", value: "Rich Communication Services" },
  { key: "RFC", value: "Request for Comments" },
  { key: "RFID", value: "Radio Frequency Identifier" },
  {
    key: "RIPEMD",
    value: "RACE Integrity Primitives Evaluation Message Digest",
  },
  { key: "ROI", value: "Return on Investment" },
  { key: "RPO", value: "Recovery Point Objective" },
  { key: "RSA", value: "Rivest, Shamir, & Adleman" },
  { key: "RTBH", value: "Remote Triggered Black Hole" },
  { key: "RTO", value: "Recovery Time Objective" },
  { key: "RTOS", value: "Real-Time Operating System" },
  { key: "RTP", value: "Real-Time Transport Protocol" },
  { key: "S/MIME", value: "Secure/Multipurpose Internet Mail Exchanger" },
  { key: "SaaS", value: "Software as a Service" },
  { key: "SAE", value: "Simultaneous Authentication of Equals" },
  { key: "SAML", value: "Security Assertions Markup Language" },
  { key: "SAN", value: "Subject Alternative Name" },
  { key: "SCADA", value: "System Control and Data Acquisition" },
  { key: "SCAP", value: "Security Content Automation Protocol" },
  { key: "SCEP", value: "Simple Certificate Enrollment Protocol" },
  { key: "SDK", value: "Software Development Kit" },
  { key: "SDLC", value: "Software Development Life Cycle" },
  { key: "SDLM", value: "Software Development Life-cycle Methodology" },
  { key: "SDN", value: "Software Defined Networking" },
  { key: "SDV", value: "Software Defined Visibility" },
  { key: "SED", value: "Self-Encrypting Drives" },
  { key: "SEH", value: "Structured Exception Handler" },
  { key: "SFTP", value: "Secured File Transfer Protocol" },
  { key: "SHA", value: "Secure Hashing Algorithm" },
  { key: "SHTTP", value: "Secure Hypertext Transfer Protocol" },
  { key: "SIEM", value: "Security Information and Event Management" },
  { key: "SIM", value: "Subscriber Identity Module" },
  { key: "SIP", value: "Session Initiation Protocol" },
  { key: "SLA", value: "Service Level Agreement" },
  { key: "SLE", value: "Single Loss Expectancy" },
  { key: "SMS", value: "Short Message Service" },
  { key: "SMTP", value: "Simple Mail Transfer Protocol" },
  { key: "SMTPS", value: "Simple Mail Transfer Protocol Secure" },
  { key: "SNMP", value: "Simple Network Management Protocol" },
  { key: "SOAP", value: "Simple Object Access Protocol" },
  { key: "SOAR", value: "Security Orchestration, Automation, Response" },
  { key: "SoC", value: "System on Chip" },
  { key: "SOC", value: "Security Operations Center" },
  { key: "SPF", value: "Sender Policy Framework" },
  { key: "SPIM", value: "Spam over Internet Messaging" },
  { key: "SQL", value: "Structured Query Language" },
  { key: "SQLi", value: "SQL Injection" },
  { key: "SRTP", value: "Secure Real-Time Protocol" },
  { key: "SSD", value: "Solid State Drive" },
  { key: "SSH", value: "Secure Shell" },
  { key: "SSL", value: "Secure Sockets Layer" },
  { key: "SSO", value: "Single Sign On" },
  { key: "STIX", value: "Structured Threat Information eXchange" },
  { key: "STP", value: "Shielded Twisted Pair" },
  { key: "SWG", value: "Secure Web Gateway" },
  { key: "TACACS+", value: "Terminal Access Controller Access Control System" },
  {
    key: "TAXII",
    value: "Trusted Automated eXchange of Indicator Information",
  },
  { key: "TCP/IP", value: "Transmission Control Protocol/Internet Protocol" },
  { key: "TGT", value: "Ticket Granting Ticket" },
  { key: "TKIP", value: "Temporal Key Integrity Protocol" },
  { key: "TLS", value: "Transport Layer Security" },
  { key: "TOTP", value: "Time-based One Time Password" },
  { key: "TPM", value: "Trusted Platform Module" },
  { key: "TSIG", value: "Transaction Signature" },
  { key: "TTP", value: "Tactics, Techniques, and Procedures" },
  { key: "UAT", value: "User Acceptance Testing" },
  { key: "UAV", value: "Unmanned Aerial Vehicle" },
  { key: "UDP", value: "User Datagram Protocol" },
  { key: "UEFI", value: "Unified Extensible Firmware Interface" },
  { key: "UEM", value: "Unified Endpoint Management" },
  { key: "UPS", value: "Uninterruptable Power Supply" },
  { key: "URI", value: "Uniform Resource Identifier" },
  { key: "URL", value: "Universal Resource Locator" },
  { key: "USB", value: "OTG USB On The Go" },
  { key: "UTM", value: "Unified Threat Management" },
  { key: "UTP", value: "Unshielded Twisted Pair" },
  { key: "VBA", value: "Visual Basic" },
  { key: "VDE", value: "Virtual Desktop Environment" },
  { key: "VDI", value: "Virtual Desktop Infrastructure" },
  { key: "VLAN", value: "Virtual Local Area Network" },
  { key: "VLSM", value: "Variable Length Subnet Masking" },
  { key: "VM", value: "Virtual Machine" },
  { key: "VoIP", value: "Voice over IP" },
  { key: "VPC", value: "Virtual Private Cloud" },
  { key: "VPN", value: "Virtual Private Network" },
  { key: "VTC", value: "Video Teleconferencing" },
  { key: "WAF", value: "Web Application Firewall" },
  { key: "WAP", value: "Wireless Access Point" },
  { key: "WEP", value: "Wired Equivalent Privacy" },
  { key: "WIDS", value: "Wireless Intrusion Detection System" },
  { key: "WIPS", value: "Wireless Intrusion Prevention System" },
  { key: "WORM", value: "Write Once Read Many" },
  { key: "WPA", value: "WiFi Protected Access" },
  { key: "WPS", value: "WiFi Protected Setup" },
  { key: "WTLS", value: "Wireless TLS" },
  { key: "XaaS", value: "Anything as a Service" },
  { key: "XML", value: "Extensible Markup Language" },
  { key: "XOR", value: "Exclusive Or" },
  { key: "XSRF", value: "Cross-Site Request Forgery" },
  { key: "XSS", value: "Cross-Site Scripting" },
];

export const ports: PortObjectArray = [
  {
    "unsecure protocol": "DNS",
    "original port": "UDP/TCP 53",
    "secure protocol": "DNSSEC",
    "secure port": "UDP/TCP 53",
    notes: "",
  },
  {
    "unsecure protocol": "FPT",
    "original port": "TCP 21 AND 20",
    "secure protocol": "FTPS",
    "secure port": "TPC 21 EXPLICIT MODE 990 IMPLICIT MODE FTPS",
    notes: "USING TLS",
  },
  {
    "unsecure protocol": "FPT",
    "original port": "TCP 21 AND 20",
    "secure protocol": "SFTP",
    "secure port": "TCP 22 (SSH)",
    notes: "USING SSH",
  },
  {
    "unsecure protocol": "HTTP",
    "original port": "TCP 80",
    "secure protocol": "HTTPS",
    "secure port": "TCP 443",
    notes: "USING TSL",
  },
  {
    "unsecure protocol": "IMAP",
    "original port": "TCP 143",
    "secure protocol": "IMAPS",
    "secure port": "TCP 993",
    notes: "USING TSL",
  },
  {
    "unsecure protocol": "LDAP",
    "original port": "UDP AND TCP 389",
    "secure protocol": "LDAPS",
    "secure port": "TCP 636",
    notes: "USING TSL",
  },
  {
    "unsecure protocol": "POP3",
    "original port": "TCP 100",
    "secure protocol": "POP3",
    "secure port": "TCP 995",
    notes: "USING TSL",
  },
  {
    "unsecure protocol": "RTP",
    "original port": "UDP 16384-32767",
    "secure protocol": "SRTP",
    "secure port": "UDP 5004",
    notes: "",
  },
  {
    "unsecure protocol": "SNMP",
    "original port": "UDP 161/162",
    "secure protocol": "SNMPv3",
    "secure port": "UDP 161/162",
    notes: "",
  },
  {
    "unsecure protocol": "TELNET",
    "original port": "TCP 23",
    "secure protocol": "SSH",
    "secure port": "TCP 22",
    notes: "",
  },
];
